### ISSUE TITLE
Broken in 0.101.0b0

### ISSUE THREAD

**Issue by VDRainer** [custom-cards/gauge-card#3]
TypeError: entity is undefined     gauge-card.js:154:7
    _getEntityStateValue gauge-card.js:154
    set hass gauge-card.js:162
    _createCardElement hui-stack-card.ts:78
    _rebuildCard hui-stack-card.ts:96
    _createCardElement hui-stack-card.ts:85
    r fire_event.ts:76
    ya create-card-element.ts:111

**Comment by iantrich** [comment]
Entity undefined sounds like an issue with your instance. Sure the entity still exists?

**Comment by VDRainer** [comment]
Thanks Ian, you're absolutely right.
There was a [broken esphome node](https://discordapp.com/channels/330944238910963714/427516175237382144/636687159457480715) which was the problem.
